version: "3.3"
services:
  papers-tests:
    image: papers-tests
    environment:
      HMAC_SECRET_KEY: d84f6e8740cc7803518b1e890c4324afe1ee154500beb61ab7bce1f430972e3b
      DATABASE_URI: postgres://db # postgres://papers:abcd@postgres/database
      PGUSER: papers
      PGPASSWORD: abcd
      PGDATABASE: database
    depends_on:
      - db
  db:
    image: postgres:14.1
    environment:
      POSTGRES_USER: papers
      POSTGRES_PASSWORD: abcd
      POSTGRES_DB: database

networks:
    internal:
        driver: bridge
